Staging: irda: net: Do not initialise statics to NULL
There is no need to initialize static variables to NULL
because they are stored in .bss segment. This segment
is initialized to 0 at the beginning of the code execution.

Issue found by checkpatch.pl.
ERROR: do not initialise statics to NULL

Signed-off-by: Georgiana Chelu <georgiana.chelu93@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>