gpio: fix kernel-doc after devres.c file rename
Fix gpio kernel-doc generation after rename of the devres.c file.
Fixes these errors & warning:

Error: Cannot open file ../drivers/gpio/devres.c
Error: Cannot open file ../drivers/gpio/devres.c
WARNING: kernel-doc '../scripts/kernel-doc -rst -enable-lineno -export ../drivers/gpio/devres.c' failed with return code 2

Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Linus Walleij <linus.walleij@linaro.org>