sh: add missing EXPORT_SYMBOL() for __delay
__delay() is used from kernel module.
We need EXPORT_SYMBOL(), otherwise we will get compile error.

ERROR: "__delay" [drivers/net/phy/mdio-cavium.ko] undefined!

Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Signed-off-by: Rich Felker <dalias@libc.org>