Revert "ARM: dts: hix5hd2: add wdg node"
This reverts commit 168d330d2bcfd8ea2d50c1a5a57bd7689dd8ef84.

"ARM: dts: hix5hd2: add wdg node" causes a build breakage due to
an undefined constatns:

Error: arch/arm/boot/dts/hisi-x5hd2.dtsi:374.22-23 syntax error

(Don't you just looove the dtc error messages? They are so informative!)

Signed-off-by: Olof Johansson <olof@lixom.net>