Revert "net: dccp: initialize (addr,port) listening hashtable"
This reverts commit c65ab7eece5d35892b5f8fe930d4b8ad65cb3668.

Cause build failures when DCCP is modular.

ERROR: "inet_hashinfo2_init" [net/dccp/dccp.ko] undefined!

Signed-off-by: David S. Miller <davem@davemloft.net>