arm64: Fix CONFIG_64BIT leak to userspace
Commit caccd8d4d9de9a58e1a2164fba3615f40870b7c5 disabled the use of config
options in uapi headers. Use __aarch64__ which is a compiler-defined
method of obtaining the architecture instead of CONFIG_64BIT.

Fixes the following error:
    error: kernel/google/raviole/arch/arm64/include/uapi/asm/sigcontext.h:
        leak CONFIG_64BIT to user-space

Change-Id: Ie1f22679882acbc3e253316d5281287956a4febd
Signed-off-by: Fiqri Ardyansyah <fiqri191002@gmail.com>