Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit 816b165ec2eceb3f7ff49f68529586c626028e8a, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer