tracing, net: fix net tree and tracing tree merge interaction
Today's linux-next build (powerpc ppc64_defconfig) failed like this:

 In file included from net/core/skbuff.c:69:
 include/trace/skb.h:4: error: expected ')' before '(' token
 include/trace/skb.h:4: error: expected ')' before '(' token
 [...]

Caused by commit 9426aabcc946299963d5947b49a800aca60242bd ("tracing:
replace TP<var> with TP_<var>") from the tracing tree interacting with
commit ccf238f917e005799af99149a0c214ac4b32a4bf ("Network Drop Monitor:
Add trace declaration for skb frees") from the net tree.

Acked-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Ingo Molnar <mingo@elte.hu>