RDMA/hns: Fix build error again
commit 77fa2f9dcd8d8994abe501408ded29d0719b6561 upstream.

This is not the first attempt to fix building random configurations,
unfortunately the attempt in commit 6494c6823e84 ("RDMA/hns: Fix build
error") caused a new problem when CONFIG_INFINIBAND_HNS_HIP06=m and
CONFIG_INFINIBAND_HNS_HIP08=y:

drivers/infiniband/hw/hns/hns_roce_main.o:(.rodata+0xe60): undefined reference to `__this_module'

Revert commits 6494c6823e84 ("RDMA/hns: Fix build error") and
22e8be662df8 ("RDMA/hns: remove obsolete Kconfig comment") to get back to
the previous state, then fix the issues described there differently, by
adding more specific dependencies: INFINIBAND_HNS can now only be built-in
if at least one of HNS or HNS3 are built-in, and the individual back-ends
are only available if that code is reachable from the main driver.

Fixes: 6494c6823e84 ("RDMA/hns: Fix build error")
Fixes: 22e8be662df8 ("RDMA/hns: remove obsolete Kconfig comment")
Fixes: 1b9da282b09d ("RDMA/hns: Initialize the PCI device for hip08 RoCE")
Fixes: dcd02ea3da66 ("RDMA/hns: Split hw v1 driver from hns roce driver")
Link: https://lore.kernel.org/r/20191007211826.3361202-1-arnd@arndb.de
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>