parisc: Silence uninitialized variable warning in dbl_to_sgl_fcnvff()
Smatch warns that is_tiny can be used uninitialized:

    arch/parisc/math-emu/fcnvff.c:297 dbl_to_sgl_fcnvff()
    error: uninitialized symbol 'is_tiny'.

This code is very old so that suggests the bug doesn't have a huge
affect in real life.  But I've read the code and it seems like a
reasonable warning.  Either way it should be harmless to initialize it
to false and silence the static checker warning.

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Helge Deller <deller@gmx.de>