sh64: fix dma_cache_sync() compilation
This patch fixes the following compile error caused by
commit 0b86adbf4af585706a2a8391bf0efed4c4237d1a:

<--  snip  -->

...
  CC      init/main.o
In file included from /home/bunk/linux/kernel-2.6/git/linux-2.6/include/linux/dma-mapping.h:52,
                 from /home/bunk/linux/kernel-2.6/git/linux-2.6/include/linux/dmaengine.h:29,
                 from /home/bunk/linux/kernel-2.6/git/linux-2.6/include/linux/skbuff.h:29,
                 from /home/bunk/linux/kernel-2.6/git/linux-2.6/include/linux/netlink.h:155,
                 from /home/bunk/linux/kernel-2.6/git/linux-2.6/include/linux/genetlink.h:4,
                 from /home/bunk/linux/kernel-2.6/git/linux-2.6/include/net/genetlink.h:4,
                 from /home/bunk/linux/kernel-2.6/git/linux-2.6/include/linux/taskstats_kern.h:12,
                 from /home/bunk/linux/kernel-2.6/git/linux-2.6/init/main.c:46:
include2/asm/dma-mapping.h: In function 'dma_cache_sync':
include2/asm/dma-mapping.h:46: error: invalid operands to binary & (have 'void *' and 'int')
make[2]: *** [init/main.o] Error 1

<--  snip  -->

Signed-off-by: Adrian Bunk <bunk@kernel.org>
Signed-off-by: Paul Mundt <lethal@linux-sh.org>