Revert "[SCSI] cnic: fix error: implicit declaration of function ‘__symbol_get’"
This reverts commit 99a4a5cb686310cbe31b14d8ab61287671921012.

All the commit did was add a second #include of <linux/module.h> which is
the wrong fix.

Signed-off-by: James Bottomley <James.Bottomley@HansenPartnership.com>