serial: sh-sci: Fix up SH7760/SH7780/SH7785 early printk regression.
As noted by Manuel:

	Commit 5e1c8879cb5238481934f139664b43f352aaa94d ("sh: Add
	SCIF2 support for SH7763.") broke build with CONFIG_EARLY_PRINTK
	enabled for me (SH7760):

	  CC      arch/sh/kernel/early_printk.o
	/mnt/work/sh7760/kernel/linux-2.6.git/arch/sh/kernel/early_printk.c: In function 'scif_sercon_putc':
	/mnt/work/sh7760/kernel/linux-2.6.git/arch/sh/kernel/early_printk.c:84: error: implicit declaration of function 'sci_SCFDR_in'

Move the SH7763 definitions out on their own, so they don't create additional
confusion within the SH7760/SH7780/SH7785 block. Restore the deleted
SCFDR definition for these parts.

Reported-by: Manuel Lauss <mano@roarinelk.homelinux.net>
Signed-off-by: Paul Mundt <lethal@linux-sh.org>