tty/amiserial: Add missing argument for tty_unlock()
commit 64e480d721a4ddc966d9875cba1c0ac3868281dd ("tty_lock: Localise the lock")
missed that bc31abf26200badb96e067e4e291bb0df3a8dc5f ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>