of: Explicitly include linux/types.h in of_graph.h
In current -next of_graph.h fails to build due to it relying on
linux/types.h without explicitly including it:

../include/linux/of_graph.h:43:71: error: unknown type name 'u32'

caused by 31fe27c1d2cc (of: Add of_graph_get_port_by_id function).  Add
an explicit inclusion to fix this.

Signed-off-by: Mark Brown <broonie@kernel.org>
Acked-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Acked-by: Philipp Zabel <p.zabel@pengutronix.de>
Signed-off-by: Rob Herring <robh@kernel.org>