PCI: label: Fix compilation error when CONFIG_ACPI is unset
This patch fixes compilation error descibed below introduced by
the commit be5bb1f75a0b17c25f7e28c860c07f6c3eaf4698

drivers/pci/pci-label.c: In function ‘pci_create_firmware_label_files’:
drivers/pci/pci-label.c:366:2: error: implicit declaration of function ‘device_has_dsm’

Signed-off-by: Narendra K <narendra_k@dell.com>
Signed-off-by: Jesse Barnes <jbarnes@virtuousgeek.org>