Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 14d3e7ce7b252f2a700bd0bbc8397a7d04bb91d1.

Commit 14d3e7ce7b25 results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 14d3e7ce7b25 ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>