gpio: gpio-mxc: Include "<linux/err.h>"
Commit 00a5e0b9 (gpio: gpio-mxc: Use devm functions) causes the following build
error on imx_v4_v7_defconfig:

drivers/gpio/gpio-mxc.c:414:2: error: implicit declaration of function 'IS_ERR' [-Werror=implicit-function-declaration]
drivers/gpio/gpio-mxc.c:415:3: error: implicit declaration of function 'PTR_ERR' [-Werror=implicit-function-declaration]

Note: imx_v6_v7_defconfig does not give this build error, probably due to some
indirect header file inclusion.

Reported-by: Olof Johansson <olof@lixom.net>
Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>
Signed-off-by: Linus Walleij <linus.walleij@linaro.org>