UPSTREAM: remoteproc: sysmon: fix shutdown_acked state
The latest version of sysmon_stop() starts by initializing
the sysmon->shutdown_acked variable, but then overwrites it
with an uninitialized variable later:

drivers/remoteproc/qcom_sysmon.c:551:11: error: variable 'acked' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        else if (sysmon->ept)
                 ^~~~~~~~~~~
drivers/remoteproc/qcom_sysmon.c:554:27: note: uninitialized use occurs here
        sysmon->shutdown_acked = acked;
                                 ^~~~~

Remove the local 'acked' variable again and set the state directly.

Fixes: 5c212aaf5457 ("remoteproc: sysmon: Expose the shutdown result")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20201204193740.3162065-1-arnd@kernel.org
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
Change-Id: Ia00e6bf5bdf4bf15aa6a4ae81eb64363005e02ec
Git-commit: 9d7b4a40387d0f91512a74caed6654ffa23d5ce4
Git-repo: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
[sidgup@codeaurora.org: cherry pick to fix compilation issue]
Signed-off-by: Siddharth Gupta <sidgup@codeaurora.org>